package com.wurmcraft.serveressentials.api.command;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Allows for the connection / automatic registration of a the command and Server-Essentials modules
 *
 * @see ModuleCommand
 */
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.TYPE)
public @interface Command {

  /**
   * Name of the module this command is going to be registered under.
   *
   * <p>the moduleName is auto used for the generation of a permissionNode
   * <moduleName>.<commandName>.<subCommand> if subCommand is even used
   *
   * @return name of the module this command is part of
   */
  String moduleName() default "";

  /**
   * Override the default command permission node generated by the moduleName and commandName
   *
   * @see Command#moduleName()
   */
  String perm() default "";

  /**
   * Trusted-Users are designed to bypass all permissions even when the database is down or
   * something has messed up the server's rank, its basically a failsafe for admins so they are able
   * to run commands even if the server has entered an apocalypse and somehow still has
   * Server-Essentials
   *
   * @return the command requires trusted user status
   */
  boolean trustedRequired() default false;
}
