package wurmcraft.serveressentials.common.reference;

public class Perm {

	public static final String COMMAND_SET_HOME = "teleport.setHome";
	public static final String COMMAND_HOME = "teleport.home";
	public static final String COMMAND_DELETE_HOME = "teleport.deleteHome";
	public static final String COMMAND_SET_WARP = "admin.setWarp";
	public static final String COMMAND_WARP = "teleport.warp";
	public static final String COMMAND_DELETE_WARP = "admin.deleteWarp";
	public static final String COMMAND_SETSPAWN = "admin.setSpawn";
	public static final String COMMAND_SPAWN = "teleport.spawn";
	public static final String COMMAND_INVSEE = "admin.invsee";
	public static final String COMMAND_ENDER_CHEST = "admin.enderChest";
	public static final String COMMAND_SUDO = "admin.sudo";
	public static final String COMMAND_SEEN = "common.seen";
	public static final String COMMAND_HEAL = "admin.heal";
	public static final String COMMAND_GAMEMODE = "admin.gamemode";
	public static final String COMMAND_RULES = "common.rules";
	public static final String COMMAND_ADD_RULES = "admin.addRules";
	public static final String COMMAND_DELETE_RULE = "admin.removeRules";
	public static final String COMMAND_MOTD = "common.motd";
	public static final String COMMAND_ADD_MOTD = "admin.addMotd";
	public static final String COMMAND_DELETE_MOTD = "admin.deleteMotd";
	public static final String COMMAND_TPA = "teleport.tpa";
	public static final String COMMAND_TPA_ACCEPT = "teleport.tpaAccept";
	public static final String COMMAND_TPA_DENY = "teleport.tpaDeny";
	public static final String COMMAND_TEAM = "common.team";
	public static final String COMMAND_TEAMADMIN = "admin.teamAdmin";
	public static final String COMMAND_CLAIM = "claim.claim";
	public static final String COMMAND_REM_CLAIM = "claim.removeClaim";
	public static final String COMMAND_FLY = "admin.fly";
	public static final String COMMAND_AFK = "common.afk";
	public static final String COMMAND_BROADCAST = "admin.broadcast";
	public static final String COMMAND_PING = "common.ping";
	public static final String COMMAND_SKULL = "admin.skull";
	public static final String COMMAND_BACK = "teleport.back";
	public static final String COMMAND_DELETE_PLAYER_DATA = "admin.deletePlayerFile";
	public static final String COMMAND_RELOAD_PLAYER_DATA = "admin.reloadPlayerData";
	public static final String COMMAND_TELEPORT = "admin.teleport";
	public static final String COMMAND_FREEZE = "admin.freeze";
	public static final String COMMAND_TOP = "admin.top";
	public static final String COMMAND_SUICIDE = "common.suicide";
	public static final String COMMAND_LIST = "common.list";
	public static final String COMMAND_RENAME = "admin.rename";
	public static final String COMMAND_CHANNEL = "common.channel";
	public static final String COMMAND_MUTE = "admin.mute";
	public static final String COMMAND_MONEY = "common.money";
	public static final String COMMAND_PAY = "common.pay";
	public static final String COMMAND_MARKET = "common.market";
	public static final String COMMAND_VAULT = "common.vault";
	public static final String COMMAND_HELP = "common.help";
	public static final String COMMAND_WEBSITE = "common.website";
	public static final String COMMAND_SPEED = "admin.speed";
	public static final String COMMAND_MESSAGE = "common.message";
	public static final String COMMAND_MAIL = "common.mail";
	public static final String COMMAND_ITEMSEND = "common.sendItem";
}
